version: '2'

services:
  node:
    build: .
    volumes:
      - "./app:/code"
    working_dir: /code
    ports:
      - "8080:8080"
  web:
    build: .
    command: npm run dev
    volumes:
      - "./app:/code"
    working_dir: /code
    ports:
      - "8080:8080"